import Link from "next/link";
import { MediaPicker } from "@/components/admin/media-picker";
import { publishSiteSettings, saveSiteSettingsDraft } from "@/lib/actions/website";
import { getAdminMediaAssets } from "@/lib/queries/admin-content";
import { getAdminSiteSettings } from "@/lib/queries/website";

export const metadata = { title: "Site settings · Admin" };

export default async function SiteSettingsPage() {
  const [{ draft, published }, assets] = await Promise.all([getAdminSiteSettings(), getAdminMediaAssets()]);
  return <><header className="admin-page-header"><p className="eyebrow">Website / Site Settings</p><h1>Site settings</h1><p>Set shared identity and search metadata while keeping the PGWINDS design system intact.</p>{published && <p className="admin-published-note">Published settings are currently live across the public website.</p>}</header><form className="admin-editor admin-editor--website" action={saveSiteSettingsDraft}><fieldset className="admin-editor__wide"><legend>General</legend><div className="admin-field-grid"><label>Website name<input name="siteName" defaultValue={draft.general.siteName} required /></label><label className="admin-field-grid__wide">Short description<input name="shortDescription" defaultValue={draft.general.shortDescription} maxLength={300} required /></label><MediaPicker name="logoMediaId" label="Logo image (optional)" assets={assets} defaultValue={draft.general.logoMediaId} /><MediaPicker name="faviconMediaId" label="Favicon image (optional)" assets={assets} defaultValue={draft.general.faviconMediaId} /></div><p className="admin-help">To change the live logo: upload the image in <Link href="/admin/media">Media</Link>, select it above, then click <strong>Publish settings</strong>. “Save draft” does not change the public website.</p></fieldset><fieldset className="admin-editor__wide"><legend>Search & sharing</legend><div className="admin-field-grid"><label className="admin-field-grid__wide">Default page title<input name="defaultTitle" defaultValue={draft.seo.defaultTitle} maxLength={180} required /></label><label className="admin-field-grid__wide">Meta description<textarea name="metaDescription" rows={4} defaultValue={draft.seo.metaDescription} maxLength={300} required /></label><MediaPicker name="ogImageMediaId" label="Social sharing image / OG image (optional)" assets={assets} defaultValue={draft.seo.ogImageMediaId} /></div></fieldset><div className="admin-editor__wide admin-form-actions"><button className="button" type="submit">Save draft (not public)</button><button className="button button--secondary" formAction={publishSiteSettings}>Publish settings</button><Link href="/">Preview published website</Link></div></form></>;
}
