import Link from "next/link";
import { createConcert } from "@/lib/actions/admin";
import { getAdminConcerts } from "@/lib/queries/admin-content";

export const metadata = { title: "Admin · Concerts" };

export default async function AdminConcertsPage() {
  const concerts = await getAdminConcerts();
  return <><header className="admin-page-header"><p className="eyebrow">Content</p><h1>Concerts</h1><p>Create an upcoming performance or prepare an archive record.</p></header><form className="admin-editor" action={createConcert}><label>Title<input name="title" required /></label><label>Slug<input name="slug" placeholder="spring-concert-2026" required pattern="[a-z0-9]+(-[a-z0-9]+)*" /></label><label>Date label<input name="displayDate" placeholder="12 October 2026" required /></label><label>Starts at<input name="startsAt" type="datetime-local" /></label><label>Venue<input name="venue" required /></label><label>Status<select name="status" defaultValue="draft"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label>Button text (optional)<input name="ctaLabel" placeholder="Learn more" /></label><label>Button link (optional)<input name="ctaUrl" placeholder="/contact or https://example.com" /></label><p className="admin-editor__wide admin-help">If you enter only a link, the button will be named “Learn more”.</p><label className="admin-editor__wide">Description<textarea name="description" rows={5} required /></label><button className="button" type="submit">Create concert</button></form><section className="admin-records"><h2>Existing concerts</h2>{concerts.length === 0 ? <p>No records yet.</p> : <div>{concerts.map((concert) => <article key={concert.id}><div><strong>{concert.title}</strong><span>{concert.displayDate} · {concert.venue}</span></div><div className="admin-record-actions"><em>{concert.status}</em><Link href={`/admin/concerts/${concert.id}`}>Edit</Link></div></article>)}</div>}</section></>;
}
