import Link from "next/link";
import { LocaleTabs } from "@/components/admin/locale-tabs";
import { MediaPicker } from "@/components/admin/media-picker";
import { publishAboutContent, saveAboutDraft } from "@/lib/actions/website";
import { getAdminMediaAssets } from "@/lib/queries/admin-content";
import { getAdminAboutContent } from "@/lib/queries/website";
import type { Locale } from "@/lib/i18n/shared";

export const metadata = { title: "About · Website Admin" };

export default async function AboutWebsiteEditorPage({ searchParams }: { searchParams: Promise<{ locale?: string }> }) {
  const locale: Locale = (await searchParams).locale === "th" ? "th" : "en";
  const [{ draft, published }, assets] = await Promise.all([getAdminAboutContent(locale), getAdminMediaAssets()]);
  const preview = locale === "th" ? "/preview/about?locale=th" : "/preview/about";
  return <><header className="admin-page-header"><p className="eyebrow">Website / About</p><h1>About page</h1><p>Edit the {locale === "th" ? "Thai" : "English"} version of the PGWINDS story.</p><LocaleTabs href="/admin/website/about" locale={locale} />{published && <p className="admin-published-note">A published {locale === "th" ? "Thai" : "English"} configuration is currently live.</p>}</header><form className="admin-editor admin-editor--website" action={saveAboutDraft}><input name="locale" type="hidden" value={locale} /><fieldset className="admin-editor__wide"><legend>Hero</legend><div className="admin-field-grid"><label className="admin-field-grid__wide">Page title<input name="heroTitle" defaultValue={draft.hero.title} required /></label><label className="admin-field-grid__wide">Intro<textarea name="heroIntro" rows={4} defaultValue={draft.hero.intro} required /></label><label>Overlay darkness<select name="heroOverlay" defaultValue={String(draft.hero.overlay)}><option value="0">None</option><option value="20">Light</option><option value="40">Medium</option><option value="60">Dark</option><option value="80">Very dark</option></select></label><MediaPicker name="heroMediaId" label="Hero background image (optional)" assets={assets} defaultValue={draft.hero.mediaId} /></div></fieldset><fieldset className="admin-editor__wide"><legend>Content sections</legend><div className="admin-field-grid"><label>History heading<input name="historyHeading" defaultValue={draft.history.heading} required /></label><label>Philosophy heading<input name="philosophyHeading" defaultValue={draft.philosophy.heading} required /></label><label className="admin-field-grid__wide">History<textarea name="historyBody" rows={6} defaultValue={draft.history.body} required /></label><label className="admin-field-grid__wide">Philosophy<textarea name="philosophyBody" rows={6} defaultValue={draft.philosophy.body} required /></label><label>Institute heading<input name="instituteHeading" defaultValue={draft.institute.heading} required /></label><label className="admin-field-grid__wide">Institute information<textarea name="instituteBody" rows={6} defaultValue={draft.institute.body} required /></label></div></fieldset><div className="admin-editor__wide admin-form-actions"><button className="button" type="submit">Save draft</button><button className="button button--secondary" formAction={publishAboutContent}>Publish About</button><Link href={preview}>Preview draft</Link><Link href={locale === "th" ? "/th/about" : "/about"}>Preview published page</Link></div></form></>;
}
